### ISSUE TITLE
Backend and maybe frontend: dirty way of storing update of user options. Improve the code

### ISSUE THREAD

**Issue by gabboman** [gabboman/wafrn#117]
Right now, the code that handles the update of user options is in the file backend/routes/users.ts, the part of the /editProfile endpoint.

There is this code wich I am not proud of
<img width="467" alt="imagen" src="https://github.com/user-attachments/assets/865b0e49-7b02-4550-b373-c78196992540">

I mean, it works but its not... "the best way of handling this". This MAY also require a change in the frontend. If you dont feel comfortable with angular, I can complete the frontend code myself and adapt to the format you consider more appropiate

**Comment by patelajay745** [comment]
I want to try this one ! So you want to  achieve the same result but with more concise code?

**Comment by gabboman** [comment]
yeah!

same result is fine, but if you make it on two queries if viable would be neat too

**Comment by gabboman** [comment]
as stated, the user options i can change how its sent too dont worry

**Comment by patelajay745** [comment]
Okay . You can assign to me . I will do backend part . I don't know angular so .
