### ISSUE TITLE
[FRONTEND] Some nsfw-marked images have 'sensitive content' warning positioned incorrectly

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#124]
On some images the 'sesitive content' warning is not overlayed on the blurred image but instead below it.

It seems as if the container for the warning overlays the alt text instead of the image

This is likely a seperate issue from the text bruaking out of its bounds on short images

example:
https://app.wafrn.net/fediverse/post/7ce6c109-c479-4296-b491-ca00af95ac6b

![Screenshot_20241012-095444](https://github.com/user-attachments/assets/d0c1bb4f-f318-4dd8-ab70-cba1043c1496)

**Comment by gabboman** [comment]
This is on wafrnmedia component.

**Comment by fluffye-yay** [comment]
another example with a slightly different manifestation

https://app.wafrn.net/fediverse/post/dddaa296-d76e-473d-8dcc-d4fdbb95368e

![Screenshot_20241020-184106](https://github.com/user-attachments/assets/c99a4fb1-80c5-410c-b652-618d0e5801b9)

**Comment by akhil02hero** [comment]
Hi @gabboman @fluffye-yay is this issue fixed , if its not can I take it up ?

**Comment by gabboman** [comment]
@akhil02hero not fixed yet :( go for it! thanks a lot

**Comment by akhil02hero** [comment]
Hi @gabboman, sure will work on it, thanks for the confirmation

**Comment by gabboman** [comment]
If you need a hand in anything there is a matrix room and a discord linked on the readme :D

**Comment by akhil02hero** [comment]
Thanks

**Comment by akhil02hero** [comment]
Raised PR: https://github.com/gabboman/wafrn/pull/143

**Comment by gabboman** [comment]
![imagen](https://github.com/user-attachments/assets/e92fc615-6302-4d5f-97cf-a85c5a6c176c)
