### ISSUE TITLE
[FRONTEND] Unaswered asks counter bubble not visible from notifications page

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#132]
When in the notifications tab, the counter bubble for unaswered asks is not visible, both on the hamburger menu button and on the menu option.

When on notifications page:
![Screenshot_20241027-103222](https://github.com/user-attachments/assets/acb72472-0573-4cad-90a3-b19b1d78be88)

When on any other page:
![Screenshot_20241027-103227](https://github.com/user-attachments/assets/df7453b4-c33c-445c-8e95-2827f404b707)

**Comment by gabboman** [comment]
Confirmed bug, I think navigating to this page makes all the badges go to zero
