### ISSUE TITLE
[FRONTEND] Long usernames break out of bounds in post view

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#134]
Long usernames break out of bounds in the post view. the solution is to apply an x-overflow css rule to the element.

![Screenshot_20241028-182701](https://github.com/user-attachments/assets/441f06f8-2591-43cb-9ed7-a1b7fadf546f)

https://app.wafrn.net/fediverse/post/4ebae6e3-1b1c-4f8b-81cb-6b1c96b4b4c4

**Comment by FireIsGood** [comment]
Seems the rewoot/etc stuff at the bottom needs to `flex-wrap` and also to have a `row-gap`. Potentially also remove the right margin on the image and just use `column-gap` as well.

![image](https://github.com/user-attachments/assets/3eade956-3619-42c4-a772-aabf43c0e2ef)

**Comment by FireIsGood** [comment]
Seems to be correct.

CSS game: Which of the following are fixed? Truly a mystery...

![image](https://github.com/user-attachments/assets/c4d2fd83-c4af-4f60-90d5-e76ae6423276)

(Ignore how I forgot to fix one of them to have `mr-1`)

I found the file to fix at [packages/frontend/src/app/pages/forum/forum.component.html line 30](../blob/main/packages/frontend/src/app/pages/forum/forum.component.html#L30). Pull request soon&trade;!!
