### ISSUE TITLE
[FRONTEND] image description overflow hidden, change to break-word

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#162]
if image description overflows in x direction it is hidden. should be changed to `break-word` to prevent text loss

https://app.wafrn.net/fediverse/post/82cc9878-af70-47f4-82b0-2c02553d6427

![Screenshot_20241207-140628](https://github.com/user-attachments/assets/3db8af75-cacd-4c52-a8ae-e21da028298d)

note copied text in bottom left is section from end of line 5, start of line 6. shows part that is hidden

**Comment by FireIsGood** [comment]
Should be working, can you confirm and close this issue is that is true?

**Comment by fluffye-yay** [comment]
yes works properly https://app.wafrn.net/fediverse/post/f5f03c0c-0782-4105-b389-d3b260a06fa8
