### ISSUE TITLE
[frontend] dark scheme home button incorrect coloration

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#168]
on dark color mode the 'home' icon button is colored white whereas all other buttons are colored dark.

notably (especially noticeable on profile pages) the color only changes to white after post(s) are loaded

this color matches the light scheme & there is no problem then

![Screenshot_20241222-215410](https://github.com/user-attachments/assets/c21ad9c5-c0a1-4f32-9946-18ad398b2dc1)

**Comment by FireIsGood** [comment]
Yep found the issue. It was something to do with two hacks:

- Emoji reacts using a `<style>` tag with unconstrained styles
- The hack in `style.scss` forgetting the to fix that specific button

This is actually why the home button looks fine when signed out or on users with really long bios that prevent posts from initially loading!

Will be fixed soon&trade;!!
