### ISSUE TITLE
[frontend] name overflow

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#195]
on posts the name of a user may overflow the container.
![Screenshot_20241227-084235](https://github.com/user-attachments/assets/1db0cb39-6c23-4d93-a480-cd33de5367e3)

**Comment by FireIsGood** [comment]
sorry! fixed in #193

**Comment by fluffye-yay** [comment]
still present, dunno if it hasnt actually been fixed or if the fix just hasnt got to me

![Screenshot_20241227-162500](https://github.com/user-attachments/assets/ecba2e69-86f8-42d5-a7c6-e0871597d95e)
