### ISSUE TITLE
Report post dialogue doesn't close (mobile, maybe PC)

### ISSUE THREAD

**Issue by Mindcool25** [gabboman/wafrn#20]
Accidentally hit the report button, the dialogue opened up and wouldn't close when I hit the x 
(I'll probably take a look into the code, I'm just not home right now so I'm adding an issue as to not forget)

**Comment by gabboman** [comment]
can confirm, and can confirm the bug has been there for a loooooooong time. Fixing old small bugs is less fun than new small features or small performance improvements, but yeah should fix this

**Comment by Mindcool25** [comment]
Fair enough, I can take a look at it when I get home and see if I can fix it

**Comment by gabboman** [comment]
<p-dialog [visible]="postToReport" header="Report a post" [modal]="true"  >
the [] should be [()] or ([]) i dont rememmber now.

**Comment by gabboman** [comment]
in the visible thingy

**Comment by gabboman** [comment]
Issue has been fixed in this commit

https://github.com/gabboman/wafrn/commit/c3f257d8a4b415884486f8bdbd8bc9cac590ee6e
