### ISSUE TITLE
[frontend] hamburger menu button notifications bubble nan

### ISSUE THREAD

**Issue by fluffye-yay** [gabboman/wafrn#206]
![Screenshot_20241228-075009](https://github.com/user-attachments/assets/085bd0c0-4fed-4440-a9cc-a7f4cfb2f0c8)

2 notifications. probably unrelated but they are for a post with contents "undefined"

**Comment by fluffye-yay** [comment]
definitely unrerelated: still shows after clearing notifications

**Comment by gabboman** [comment]
full reload, should not happen on latest update of the frontend

**Comment by fluffye-yay** [comment]
yep seems to be the case

**Comment by gabboman** [comment]
fixed?

**Comment by fluffye-yay** [comment]
> fixed?

yes
