### ISSUE TITLE
Objects should return Content-Type of "application/activity+json"

### ISSUE THREAD

**Issue by ddvarpdd** [gabboman/wafrn#32]
See [chapter 3.2 of ActivityPub spec](https://www.w3.org/TR/activitypub/#retrieving-objects).
Right now it returns Content-Type of "application/json; charset=utf-8", which breaks federation with servers that expect the proper header, such as Pleroma.

**Comment by gabboman** [comment]
I will investigate, thanks a lot and sorry

**Comment by ddvarpdd** [comment]
I was talking about the AP object endpoint, /fediverse/post/{UUID}. Looks like sometimes the endpoint returns correct header, but all subsequent requests return application/json which sounds a lot like some caching middleware issue.

Tried some random post (`curl -v -H "Accept: application/activity+json" https://app.wafrn.net/fediverse/post/b4449a6f-ce5e-4ba3-a88a-51c9633a3fef`), first request returned `Content-Type: application/activity+json; charset=utf-8`, second one returned `Content-Type: application/json; charset=utf-8` while still returning the same data.

**Comment by gabboman** [comment]
It is cache, you're right. Will investigate. Thanks a lot

**Comment by gabboman** [comment]
Updated library. now seems to do properly. Will update the instnace later
