### ISSUE TITLE
Wafrn sending messages to all instances?

### ISSUE THREAD

**Issue by JD557** [gabboman/wafrn#34]
I run a small [microblog.pub](https://microblog.pub/) instance at https://blog.joaocosta.eu, and today I started to receive multiple messages in my inbox from wafrn users.

I don't follow nor am followed by anyone from Wafrn, so I assume my instance was somehow discovered by Wafrn and it sends messages to all known instances? Looking at https://github.com/friendica/friendica/issues/13152#issuecomment-1566179752, I think this already happened in the past.

Either way, here's an example message:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount",
      "blurhash": "toot:blurhash",
      "focalPoint": {
        "@container": "@list",
        "@id": "toot:focalPoint"
      }
    }
  ],
  "id": "https://app.wafrn.net/fediverse/activity/post/bab28b15-8df7-47c6-b0fe-a8de481b2fcb",
  "type": "Create",
  "actor": "https://app.wafrn.net/fediverse/blog/gabboman",
  "published": "2023-07-04T21:00:30.000Z",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://app.wafrn.net/fediverse/blog/gabboman/followers"
  ],
  "cc": [],
  "object": {
    "id": "https://app.wafrn.net/fediverse/post/bab28b15-8df7-47c6-b0fe-a8de481b2fcb",
    "type": "Note",
    "summary": "",
    "inReplyTo": "https://app.wafrn.net/fediverse/post/627f1e9f-6ab8-48bf-bba2-5243203a105a",
    "published": "2023-07-04T21:00:30.000Z",
    "url": "https://app.wafrn.net/fediverse/post/bab28b15-8df7-47c6-b0fe-a8de481b2fcb",
    "attributedTo": "https://app.wafrn.net/fediverse/blog/gabboman",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public",
      "https://app.wafrn.net/fediverse/blog/gabboman/followers"
    ],
    "cc": [],
    "sensitive": false,
    "atomUri": "https://app.wafrn.net/fediverse/post/bab28b15-8df7-47c6-b0fe-a8de481b2fcb",
    "inReplyToAtomUri": "https://app.wafrn.net/fediverse/post/627f1e9f-6ab8-48bf-bba2-5243203a105a",
    "content": "<p>update no i wont, they dont wana comply with gdpr</p><br>",
    "attachment": [],
    "tag": []
  },
  "signature": {
    "type": "RsaSignature2017",
    "creator": "https://app.wafrn.net/fediverse/blog/gabboman",
    "domain": "app.wafrn.net",
    "nonce": "dd2e984d76aaa0ec798f6661526917d5",
    "created": "2023-07-04T21:00:30.000Z",
    "signatureValue": "KlP1L7wnsd0yv35LvBo07MVG8KgTHExBiV75e5IJUjKi1LZcOEei0+PkUMZK44KSmOUv15BN7h8VuMPV3E1vbytgtFUE0TsN+6usSg3LrxZLvYJJXZOkyOzZ/o3QRaBQlgIfDBlKhb5Yjg5JhVBfU8jnuDEKB3QjxxzUEwnd4MSedtmysA3cpZS2sh0fM9pX7ZGbtohfuUrF5n/nLZkN0GSZDZvzdGL0tfNgyHvkXVvmxi/oE7tp7SlZ/0wpFtA5cHJK30+6CajdhAp5hUa0X9uSSlXRrbS98Vyn3fTkNkrpzvz4VTYS2IF5iq5oUKgqUFF6NFyX4VLZDZXpLjIjc6ewuSHvjXIe+8D+l6gNbIZ8ZWh7E/XbNjwXGjVubocyFUyZOV5sN+zf83O4s1H8hAWnBFB2ftz0pfRkgiZEnmKrDD8j1Cy/xOxX+KeWOFkmyAuKo+rTrI0jn82edOZKIvveq8YZCa+mnxXRfAT6RZ/beMQgYMg7sfl4gmA5oBPc9hHfCkqK4AWKmj5HwN8X/cdbeD4jG6TZyBy+S4TltiRM18vaKbcEZ/cWqdLewcPzsusyOdTe1D178Vy71tJwFENWKSI1AEpPRnQiRp6rNqnmSdvc4saUJQSyvaeFfXAvtXoxtWfvA9b1PdDOfc/kMGO1jRWlD6kPj56ulxXdkF4="
  }
}
```

P.S.: I'm not sure if this is the expected behavior, but unfortunately I (and I imagine other admins from small instances) can't risk having a huge spike of traffic from wafrn and will have no choice but to defederate.

**Comment by gabboman** [comment]
OH NOT AGAIN I AM SORRY I will investigate

**Comment by gabboman** [comment]
hello @JD557 does the issue still happens? the bug of wafrn sending things incorrectly was fixed and i made it even more granular at the time of sending posts

**Comment by JD557** [comment]
I think this sill happens. It's hard for me to say since I had to block the requests (which limits my logs).

But the number of `POST /inbox` requests that I am getting for each day seem to match the number of posts on the front page.

**Comment by gabboman** [comment]
I am almost sure it's the default concept, to send to everyone the public posts. is your server that should do the things with it.

I can manually block your instance and wafrn wont do requests to yours

**Comment by JD557** [comment]
Indeed, I was taking a look and I think the problem is on my side (I just noticed that my server is using the same `inbox` and `sharedInbox` endpoint, that's why this was so confusing).

Closing this issue, sorry for taking your time.

**Comment by gabboman** [comment]
> Indeed, I was taking a look and I think the problem is on my side (I just noticed that my server is using the same `inbox` and `sharedInbox` endpoint, that's why this was so confusing).
> 
> 
> 
> Closing this issue, sorry for taking your time.

I actually am gonna need to add a way of updating servers so yep, might need to do something to detect updates in servers and stuff

**Comment by DarkRTA** [comment]
I am having this issue with wafrn sending everything to my instance as well. This should probably be reopened until its fixed.

**Comment by JD557** [comment]
I thought I had left this here, but guess not, so I'll just leave this here for future reference:

[Section 7.1.3 - Shared Inbox Delivery](https://www.w3.org/TR/activitypub/#shared-inbox-delivery)
> Additionally, if an object is addressed to the [Public](https://www.w3.org/TR/activitypub/#public-addressing) special collection, a server MAY deliver that object to all known `sharedInbox` endpoints on the network.

I'm not saying this is a good or bad practice, but it does seem to be valid according to the spec.
So I think independently on what Wafrn decides to do, you might also want to request a new Misskey feature to "discard public posts that don't address any server user" (or something like that).

**Comment by gabboman** [comment]
@DarkRTA @JD557  I've changed it and in the latest commit that I am about to push to prod it will only send to public inbox of servers where i have followers. profiles will be a lot emptier but a price to pay for doing things properly Iguess
