### ISSUE TITLE
login registration

### ISSUE THREAD

**Issue by m3t0034** [gabboman/wafrn#35]
while trying to register it asks for a birthdate which forces a datepicker which starts on July 1 2009. Attempts to change the year are a monkey test of frustration, one month at a time. can't type a date or paste a date. crap datepicker or screw this... Go ahead, try to register for your own instance. fix please! Like the looks of what I've seen

**Comment by m3t0034** [comment]
managed to figure out the crappy datepicker but there's now a problem with my login/password after the registration email was sent. something about special characters spaces... Giving up for today

**Comment by gabboman** [comment]
hello, what user did you use? I am working on a refactor of some parts and I might had fix something regarding registration last week

**Comment by m3t0034** [comment]
mikemcc5@gmail.com with a random password. got an email but link didn't work. password reset wouldn't work either.

**Comment by gabboman** [comment]
You are mared as activated. I can give you a random password if you'd like.
[https://matrix.to/#/#wafrn:matrix.org](https://matrix.to/#/#wafrn:matrix.org) or gabboman92 on discord.

**Comment by m3t0034** [comment]
Thanks for looking into this. I realised I had been trying to use m3t00 in the login blank marked email. email worked and I'm logged in. looks nice. going to look around a while. maybe could use a validation hint on the login form. Chrome usually remembers all my login stuff so hopefully that quit autofilling wrong. I was wondering why the login button wouldn't enable.

Thanks again, Mike

**Comment by m3t0034** [comment]
closed, thanks

**Comment by gabboman** [comment]
good idea. changed the type from text to form on the dev environment and will put on the next update
