### ISSUE TITLE
[Feature request] Drop-down button for notes (replies)

### ISSUE THREAD

**Issue by aquariusdev** [gabboman/wafrn#39]
Would be great to be able to see the replies (or even quotes a la Misskey/Firefish) via making the "Notes: n" text at the bottom a drop-down button like Tumblr.

**Comment by gabboman** [comment]
this feature is in the roadmap and is super easy to do. might try doing something this week or next week

**Comment by gabboman** [comment]
Feature has been added with extra fetch remote replies![image](https://github.com/gabboman/wafrn/assets/3456181/986cb581-cd4d-4106-9119-981ee3e98631)
