### ISSUE TITLE
 Implement FEP-dc88: Formatting Mathematics #2410 

### ISSUE THREAD

**Issue by gabboman** [gabboman/wafrn#40]
[FEP-dc88](https://codeberg.org/fediverse/fep/src/branch/main/fep/dc88/fep-dc88.md) has been put forward as an attempt to standardize mathematical typesetting on the fediverse. Please see the [tracking issue](https://codeberg.org/fediverse/fep/issues/161) and [forum discussion](https://socialhub.activitypub.rocks/t/fep-dc88-formatting-mathematics/3564) for more information. Glitch-soc already implements rich-text formatting, and mathematical formatting is a desired feature for it to implement (see https://github.com/glitch-soc/mastodon/issues/1432 https://github.com/glitch-soc/mastodon/issues/1934)
Motivation

Mathematical typesetting is an important tool on the fediverse, and several instances have mechanisms in place to do so. However, mathematical formatting is currently nonstandard and leads to incompatible rendering of posts between instances. [FEP-dc88](https://codeberg.org/fediverse/fep/src/branch/main/fep/dc88/fep-dc88.md) aims to create a standard for this formatting, and implementation of it would lead to a wide, compatible ecosystem of mathematical typesetting on the fediverse.

**Comment by gabboman** [comment]
lol no wont do

**Comment by 4e554c4c** [comment]
> lol no wont do

why not :pleading_face:
