### ISSUE TITLE
Broken ActivityPub interop

### ISSUE THREAD

**Issue by vitalyster** [gabboman/wafrn#41]
I receive that several times each day:
`{"@context":["https://www.w3.org/ns/activitystreams","https://app.wafrn.net/contexts/litepub-0.1.jsonld"],"actor":"https://app.wafrn.net/fediverse/blog/wubsbian","to":["https://www.w3.org/ns/activitystreams#Public","https://app.wafrn.net/fediverse/blog/wubsbian/followers"],"cc":[null],"id":"https://app.wafrn.net/fediverse/likes/96b4020d-5d44-4e2e-b595-e6b76cd0351f/1438884d-cbbe-4228-8e61-1013f7a14df1","object":null,"type":"Like"}`

1. Why I get this in my ActivityPub server inbox? I'm not in `cc`
2. Why object is null? cc is null?

**Comment by gabboman** [comment]
i fucked up thats why. I will investigate thanks and sorry

**Comment by gabboman** [comment]
hey @vitalyster fixed the issue [https://github.com/gabboman/wafrn-backend/commit/311139b6ac63bc417fefac3ea52bdd7e9005ba04](https://github.com/gabboman/wafrn-backend/commit/311139b6ac63bc417fefac3ea52bdd7e9005ba04) please let me know if it still happens

**Comment by gabboman** [comment]
also, you were reciving the object because you follow wubsian at app dot wafrn dot net.

**Comment by vitalyster** [comment]
> also, you were reciving the object because you follow wubsian at app dot wafrn dot net.

No, I did not follow anyone, my implementation does not support following at all.
That happens with other servers (Friendica, IIRC) too, but I did not find the reason.
I can provide any information which can help you to debug the issue. My server is juick dot com if that helps.

**Comment by gabboman** [comment]
I will investigate who likes get sent to, I wrote this a few months ago and I dont remember any of it. If I recall correctly likes get sent only to "followers".

I have fixed the parts of the object that are undefined tho, wich was definetly a bug

**Comment by gabboman** [comment]
Hello this issue has long been fixed
