### ISSUE TITLE
[Bug] Mobile interface on Android keeps adding newlines before the start of my post

### ISSUE THREAD

**Issue by Mieridduryn** [gabboman/wafrn#54]
**Platform:** Android, wafrn mobile website pinned to homescreen via Firefox.
**Expected behavior:** No alterations are made to my post as I am typing it.
**Unexpected behavior:** When I go to make a new post on mobile, several newlines are added before my very eyes to the start of my posts. This does not happen when I access wafrn's desktop interface on a desktop computer. This behavior is inconsistent and does not always happen.

To reproduce:
1) While on wafrn on mobile Firefox, open the menu and hit either "Install" or "Add to home screen."
2) Open the shortcut this creates.
3) Hit the button to create a new post and start typing.
4) If the bug decides to show up (I tried and failed to reproduce and record it for the sake of this bug report), several newlines will be placed in your post while you are still typing.

**Comment by Mieridduryn** [comment]
https://github.com/gabboman/wafrn/assets/155842515/fc57a6a6-43e5-416f-a82a-5c93fdf2799d

^

**Comment by gabboman** [comment]
firefox nightly or regular?

The pwa version seems to be buggy. on ios as example doesn't load external images that go through the cacher

**Comment by Mieridduryn** [comment]
Nightly.
-------- Original message --------From: Gabriel Amador García ***@***.***> Date: 1/7/24  7:06 AM  (GMT-05:00) To: gabboman/wafrn ***@***.***> Cc: Mieridduryn ***@***.***>, State change ***@***.***> Subject: Re: [gabboman/wafrn] [Bug] Mobile interface on Android keeps adding newlines before the start of my post (Issue #54) 
firefox nightly or regular?
The pwa version seems to be buggy. on ios as example doesn't load external images that go through the cacher

**Comment by gabboman** [comment]
@Mieridduryn can not reproduce. what keyboard do you use?

https://github.com/gabboman/wafrn/assets/3456181/7a486d08-2bea-479e-b440-985d1c35d59b

**Comment by Mieridduryn** [comment]
I use the default keyboard built into Samsung's OEM distribution of Android.
-------- Original message --------From: Gabriel Amador García ***@***.***> Date: 1/11/24  11:34 AM  (GMT-05:00) To: gabboman/wafrn ***@***.***> Cc: Mieridduryn ***@***.***>, Mention ***@***.***> Subject: Re: [gabboman/wafrn] [Bug] Mobile interface on Android keeps adding newlines before the start of my post (Issue #54) 
@Mieridduryn can not reproduce. what keyboard do you use?
https://github.com/gabboman/wafrn/assets/3456181/7a486d08-2bea-479e-b440-985d1c35d59b

**Comment by gabboman** [comment]
I have spoken with other people and they seem to have SOMETIMES the same issue. Its going to be hard fun to figure out what is causing this. I will investigate

**Comment by gabboman** [comment]
A big update was done to the editor, changing the version. Please let me know if it still happens
