### ISSUE TITLE
needs some visual queue for already rebllogged posts

### ISSUE THREAD

**Issue by m3t0034** [gabboman/wafrn#57]
needs some indication a post has already been reblogged/replied. similar to 'like' heart change. memory is extremely short term at times. :sneak-a-toke: :-)

**Comment by gabboman** [comment]
this would require a change in the query but you are right can be done.
It will take some time but will do!

**Comment by gabboman** [comment]
#93  by @juandjara  added some stuff into the backend for this, it will be done soon :D

**Comment by gabboman** [comment]
Implemented now so this issue can be closed
