### ISSUE TITLE
write post link dialog obscured

### ISSUE THREAD

**Issue by m3t0034** [gabboman/wafrn#58]
dialog is under below window box. css
![Screenshot_2024-02-12_21-16-38](https://github.com/gabboman/wafrn/assets/41834709/fe973444-7436-4a5f-a613-6e166c95cda1)
![Screenshot_2024-02-12_21-15-33](https://github.com/gabboman/wafrn/assets/41834709/3b28bae2-3d00-4ef1-a43d-cc6c2ea7de7c)

**Comment by elevchyt** [comment]
Can I perhaps look into this @gabboman ?

**Comment by gabboman** [comment]
> Can I perhaps look into this @gabboman ?

PLEASE HELP ME YES PLEASE DO

**Comment by elevchyt** [comment]
@gabboman I'm getting "Email or url in use" when attempting to register.
Is there a throwaway account so I can log in without awaiting admin verification?

**Comment by gabboman** [comment]
can you dm me in matrix?

@gabboman92:matrix.org


discord is ok too (gabboman92)

**Comment by elevchyt** [comment]
added you on discord

**Comment by elevchyt** [comment]
Just created a PR for this.
https://github.com/gabboman/wafrn/pull/61

**Comment by gabboman** [comment]
new fix deployed, 10/10
