### ISSUE TITLE
Hide consecutive reply-threads in profile

### ISSUE THREAD

**Issue by ShadowJonathan** [gabboman/wafrn#68]
So lets say someone is replying a bunch in a thread, and having a conversation:

1. A
2. B
3. A
4. B
5. A
6. B
7. A

This longest post would appear first in their profile

However, scrolling down, their previous replies would show up as independent threads below that:

1. A
2. B
3. A
4. B
5. A

(And)

1. A
2. B
3. A

(etc.)

----

What if instead, the frontend (or the backend) will hide these additional duplicates from the feed, allowing only a single consistent one to appear at the top?

This is easily doable:
- Remember every thread seen, note down all replies from A (the viewed profile)
- When loading an additional thread, if the latest reply is in the above noted list, skip over it, because then the user has already seen that the entire thread before when loading it.

**Comment by gabboman** [comment]
you're right, I actually do that in the regular view. Its a small change in the frontend

**Comment by gabboman** [comment]
well its a bit more than just small but its doable.

dashboard.component.ts lines 128 to 140, I would need to move that code out to the service or something like that. Will try to do this week

**Comment by gabboman** [comment]
Fixed in  commit d83f22f55bfaae2

**Comment by ShadowJonathan** [comment]
💚
