### ISSUE TITLE
inconsistent system font

### ISSUE THREAD

**Issue by coretto958** [gabboman/wafrn#70]
it switches to Helvetica (for me) when I make or reply to a post

![image_2024-04-12_224807008](https://github.com/gabboman/wafrn/assets/130465725/f86ec83d-ee22-4c25-8cec-7dac90ef2c5a)

**Comment by gabboman** [comment]
yep, thanks for the tip, seen that. its the editor's css. will force roboto in there too

**Comment by gabboman** [comment]
Issue has been fixed @coretto958
