### ISSUE TITLE
add link feature doesn't work

### ISSUE THREAD

**Issue by coretto958** [gabboman/wafrn#71]
I get prompted to add the link, and then nothing happens

https://github.com/gabboman/wafrn/assets/130465725/39c1918a-f80f-4b85-991f-7ac4bc3440ef

**Comment by gabboman** [comment]
this is an issue with quill and I will report. but you need to have something selected to make it "the link"

I should check if I can do a "did you just pasted a link?" with a regex

**Comment by gabboman** [comment]
https://github.com/gabboman/wafrn/assets/3456181/734e39d6-8aaf-45c8-ba57-452af461bfbf

example of how its intended. still I think youre right. I will write the quill people about this

**Comment by coretto958** [comment]
it seems very impractical to me

**Comment by gabboman** [comment]
I have just checked older versions of it and still happens. I might have to modify it myself or something

**Comment by gabboman** [comment]
Fixed on the new editor
