### ISSUE TITLE
minor css tweak in reply dialog. see pic

### ISSUE THREAD

**Issue by m3t0034** [gabboman/wafrn#78]
save button almost obscured when adding a link near right-side. attached:
![wafrnreplycssbug](https://github.com/gabboman/wafrn/assets/41834709/c7540e22-adf1-4085-9132-005cc575615f)

**Comment by gabboman** [comment]
yeah this is a problem with quill. I have some plans on how I display the editor and I expect to improve it soon

**Comment by gabboman** [comment]
Fixed with updates to new editor
