### ISSUE TITLE
Queuing delivery

### ISSUE THREAD

**Issue by ShadowJonathan** [gabboman/wafrn#81]
I'm seeing that https://github.com/gabboman/wafrn/blob/d7aa97d38a23af0a546a59e0ff4da26ab02aa8d9/packages/backend/utils/activitypub/postPetitionSigned.ts#L8 is basically sending the AP object in the same HTTP call as some activities (such as accepting follow requests), and i think it would be more useful to put that kind of stuff in queuing, or at least, to make sure it retries if it fails.

This'll make wafrn more resilient, especially against offline instances.

**Comment by gabboman** [comment]
I hate offline instances but youre right

**Comment by ShadowJonathan** [comment]
Some instances might be offline for 10 minutes or an hour, or maybe a day, as the admin gets prompted.

Sometimes some network failures happen (like DNS or TCP being fucked), or there being a DDoS attack on that server.

Mastodon effectively keeps retrying for a week, with 16 retries over exponential backoff, so maybe thats something to look at.

I assume you're already using queued delivery when making posts, so maybe this could hook into that?

**Comment by gabboman** [comment]
It has been fixed on the latest updates. It caused some conmotion on the code and a few bugs, but all fixed

**Comment by gabboman** [comment]
PR going stale. merging...
