### ISSUE TITLE
avatars on posts in notifications get squished sometimes

### ISSUE THREAD

**Issue by ihateblueb** [gabboman/wafrn#84]
![image](https://github.com/user-attachments/assets/10d16c19-8605-46b2-b5b8-b3c3f632d2c3)
![image](https://github.com/user-attachments/assets/9167a333-6266-4ead-964b-a12b1cdc6be2)

seems to be fixed with object-fit: cover; on the img

**Comment by gabboman** [comment]
hmmm will check and aaaaaa. my brain off today. thanks

**Comment by gabboman** [comment]
ohhh yeah the notification DID not use the component avatar-small. Fixed on bf43c04c4d2474d7a88ba35932ad730b439914df
