### ISSUE TITLE
WafrnHashtag missing from /contexts/litepub-0.1.jsonld

### ISSUE THREAD

**Issue by ihateblueb** [gabboman/wafrn#86]
there's currently no mention of WafrnHashtag in the `@context`  links.
![https://app.wafrn.net/contexts/litepub-0.1.jsonld](https://github.com/user-attachments/assets/4e4f7a20-bbb7-4acb-9aa9-f5224185796a)

**Comment by gabboman** [comment]
SO YOU WERE TESTING STUFF.

Ok, Im gonna add it to the jsonld, thanks for leting me know

**Comment by ihateblueb** [comment]
i could be wrong but i’m pretty sure that’s not how you document that
most tend to do it like this:
```json
"software": "[docs url]/ns#",
"extension": "software:extension"
```
following misskey’s contexts, i wrote my extensions like this:
```json
	"aster": "https://harper.eepy.zone/ns#",
	"visibility": "aster:visibility"
```
a while back, kopper linked me to a jsonld validator that helped a lot in making sure it was valid: https://json-ld.org/playground/
