### ISSUE TITLE
Add Tumblr style interaction info in post header 

### ISSUE THREAD

**Issue by breadguyyy** [gabboman/wafrn#89]
Screenshots for reference:
![Screenshot_20240813-155624](https://github.com/user-attachments/assets/758c8724-8a4a-486b-bb8e-d1bb378614b1)
![Screenshot_20240813-155547](https://github.com/user-attachments/assets/4d8d9de0-d52f-4edb-b73a-88fbd09ecc9e)

for instance: 
-add reblog/reply icon somewhere in the header or on the user icon
- add "[user] boosted/replied" text to show the interaction type
- add timestamp of interaction

**Comment by gabboman** [comment]
OH GOD true, I broke that! Thanks for letting me know
