### ISSUE TITLE
roundedness is cutting off corners!!! 😨

### ISSUE THREAD

**Issue by breadguyyy** [gabboman/wafrn#99]
![image](https://github.com/user-attachments/assets/e078475d-ee56-4040-b240-454390f55014)
![image](https://github.com/user-attachments/assets/07996b0c-e8fa-4744-b229-6bd75016120d)
also that second one has a scrollbar for some reason lol

**Comment by gabboman** [comment]
I cut too many corners

**Comment by gabboman** [comment]
Fixed in 7292686f6a3c68
